Repository Bruunaa/diario-viagens, pull requests merged in 2022-06, with the labels that each got.

#10 Implementacao Captcha telas Login e Cadastro
  package-lock.json
  package.json
  src/app/auth/auth.module.ts
  src/app/auth/components/cadastro/cadastro.component.html
  src/app/auth/components/cadastro/cadastro.component.ts
  src/app/auth/components/login/login.component.html
  src/app/auth/components/login/login.component.ts
Labels: enhancement

#29 Atualização de arquivos para o deploy
  angular.json
  firebase.json
  package.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: wontfix

#31 Adição msg Entrada e Despedida App
  src/app/auth/components/login/login.component.ts
  src/app/core/components/navbar/navbar.component.ts
Labels: documentation, enhancement

#36 Atualização usuario com link
  src/app/app.module.ts
  src/app/auth/auth-routing.module.ts
  src/app/diarios/components/diario-list/diario-list.component.html
  src/app/diarios/components/diario-list/diario-list.component.scss
  src/app/diarios/components/diario-list/diario-list.component.ts
  src/app/diarios/diarios-routing.module.ts
  src/app/diarios/diarios.module.ts
  src/app/usuario/usuario.component.html
Labels: documentation
